---
- hosts: webservers
  remote_user: vagrant
  roles:
    - { role: rvm.ruby,
        tags: ruby,
        rvm1_rubies: ['ruby-2.3.1'],
        rvm1_bundler_install: True,
        rvm1_user: vagrant
      }
  environment:
    PATH: "{{ ansible_env.HOME }}/.rvm/gems/ruby-{{ ruby_version }}/bin:\
           {{ ansible_env.HOME }}/.rvm/gems/ruby-{{ ruby_version }}@global/bin:\
           {{ ansible_env.HOME }}/.rvm/rubies/ruby-{{ ruby_version }}/bin:\
           {{ ansible_env.HOME }}/.rvm/bin:\
           {{ lookup('env', 'PATH') }}"
    GEM_PATH: "{{ ansible_env.HOME }}/.rvm/gems/ruby-{{ ruby_version }}:\
                     {{ ansible_env.HOME }}/.rvm/gems/ruby-{{ ruby_version }}@global"

  vars:
    packages: ["git"]
    repo_url:  https://github.com/alexrochas/fake-service.git
    repo_remote: origin
    ruby_version: 2.3.1
    repo_version: master
    app_dir: "{{ ansible_env.HOME }}/fake-service"

  tasks:
    - name: Update repositories cache and install "git" package
      yum:
        name: git-all
        update_cache: yes
      become: yes
      become_user: root

    - name: git pull project
      git: repo={{repo_url}} dest={{app_dir}} version=master

    - gem:
        name: bundler

    - bundler:
        gemfile: "{{app_dir}}/Gemfile"
        state: present
        executable: "{{ ansible_env.HOME }}/.rvm/gems/ruby-{{ ruby_version }}/bin/bundler"
        gem_path: "{{ ansible_env.HOME }}/.rvm/gems/ruby-{{ ruby_version }}"

    - name: Start sinatra
      shell: bundle exec ruby fake-service.rb  </dev/null >/dev/null 2>&1 &
      args:
        chdir: "{{app_dir}}/"



